Homework 23
krottv/AN14-Android pull request #21
Opened 2022-04-20 09:26 UTC by AleksandrKalevich

![photo_2022-04-20_12-24-30](https://user-images.githubusercontent.com/98311174/164196894-5211db61-c9bd-40bf-9dae-85d8af1796be.jpg)
![photo_2022-04-20_12-24-30 (2)](https://user-images.githubusercontent.com/98311174/164196943-c2de1dfc-4e59-4332-9e67-8267928e5914.jpg)
![photo_2022-04-20_12-24-30 (3)](https://user-images.githubusercontent.com/98311174/164196992-48ff28eb-9e4b-4a26-ad46-0fb9ca498eda.jpg)

2022-04-20 10:45 UTC, krottv commented
Нужен другой scaleType у imageView @AleksandrKalevich

2022-04-20 10:50 UTC, krottv requested changes
В целом, отлично, есть пару комментов

2022-04-20 10:50 UTC, krottv commented on app/src/main/java/com/github/krottv/tmstemp/binder/MainActivityRecyclerScrollDataBinder.kt
> +        element.data = element.data.subList(1, element.itemCount)
Это лучше сделать как отдельная функция внутри MessageAdapter. Совершение таких операций из вне грозит ошибками потенциальными

2022-04-20 10:50 UTC, krottv commented on app/src/main/java/com/github/krottv/tmstemp/binder/MainActivityRecyclerScrollDataBinder.kt
> +    fun showError() {
Сюда стоит как параметр передать exception и отображать сообщение именно этой ошибки.

2022-04-20 12:37 UTC, AleksandrKalevich commented
![Screenshot from 2022-04-20 15-36-12](https://user-images.githubusercontent.com/98311174/164231919-17e0c0a2-ba56-4325-8988-6cf801095a28.png)

2022-04-21 07:00 UTC, krottv approved these changes
Good

2022-04-24 21:38 UTC, closed without merging