Homework 17 by Alexandr Kalevich
krottv/AN14-Android pull request #3
Opened 2022-03-30 00:10 UTC by AleksandrKalevich

Единственная проблема, что когда мы трансформ делаем и меняем ориентацию экрана, то все трансформы пропадают и массив заново создается, как мутбл лист передавать читал, но там либо библиотеки предлагают, либо я не понял

2022-03-30 04:35 UTC, krottv requested changes

2022-03-30 04:35 UTC, krottv commented on app/src/main/java/com/github/krottv/tmstemp/MainActivity.kt
> +    var students = listOf(Student(18,1,"Lex"),
Переменная неизменяемая должна быть val, as MutableList тоже не нужно

2022-03-30 10:37 UTC, AleksandrKalevich commented on app/src/main/java/com/github/krottv/tmstemp/MainActivity.kt
> +    var students = listOf(Student(18,1,"Lex"),
так как поменял на ArrayList, то пришлось оставить переменную как var

2022-03-31 04:25 UTC, krottv commented on app/src/main/java/com/github/krottv/tmstemp/MainActivity.kt
> +    var students = listOf(Student(18,1,"Lex"),
Так а зачем var? Сама переменная не перезаписывается в коде больше.

2022-03-31 04:27 UTC, krottv commented on app/src/main/java/com/github/krottv/tmstemp/MainActivity.kt
> +        numberOfStudent = savedInstanceState.getInt("numberOfStudent")
numberOfStudent думаю надо после students менять, чтобы отобразились актуальные данные

2022-03-31 10:03 UTC, AleksandrKalevich commented on app/src/main/java/com/github/krottv/tmstemp/MainActivity.kt
> +        numberOfStudent = savedInstanceState.getInt("numberOfStudent")
все поправил, теперь корректно все работает

2022-04-04 06:25 UTC, krottv approved these changes
Good

2022-04-24 21:38 UTC, closed without merging